---
driver:
  name: vagrant
  customize:
    memory: 4000
    natdnshostresolver1: "on"
    natdnsproxy1: "on"

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.4.3

platforms:
  - name: ubuntu-14.04
#  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[kagent::install]
      - recipe[charon::install]
      - recipe[charon::default]

    attributes:
         kagent:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         charon:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
         vagrant: "enabled"

