---
driver:
  name: vagrant
  customize:
    memory: 4000
    natdnshostresolver1: "on"
    natdnsproxy1: "on"

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.4.3

platforms:
  - name: ubuntu-14.04
#  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[kagent::install]
      - recipe[charon::install]
      - recipe[charon::default]

    attributes:
         charon:
            default:
                private_ips: ["10.0.2.15"]
            user: glassfish
            group: hadoop
            user_email: jdowling@kth.se
            use_only_aws: true
            access_key: <%= ENV['AWS_ACCESS_KEY_ID'] %>
            secret_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
            conf_dir: "/srv/hadoop/etc/hadoop"
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
         vagrant: "enabled"

